### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by leaumar** [lpinca/forwarded-parse#4]
I tried to use this library in my typescript project but it lacks included type mappings and is not included in DefinitelyTyped either.

I wrote the following .d.ts myself for my project and compared it to forwarded-parse's behavior, it appears to be a good match.

Please include it in your project. I believe just adding `index.d.ts` to the files root is all it takes, but I'm no expert on publishing typed libraries.

```typescript
declare module "forwarded-parse" {
    export interface Entry {
        by?: string;
        for?: string;
        host?: string;
        proto?: string;
    }

    export default function parseForwarded(forwarded: string): Entry[];
}
```

**Comment by lpinca** [comment]
Please open a PR on the DefinitelyTyped repository. I don't want to maintain TypeScript type definitions.

**Comment by leaumar** [comment]
All that overhead for 1 function that hasn't changed in 3 years and probably never will? :/

**Comment by leaumar** [comment]
Thank you!
