### ISSUE TITLE
Spoofing of left values leads to complete failure

### ISSUE THREAD

**Issue by adam-p** [lpinca/forwarded-parse#6]
It is typically the case that the rightmost-ish `Forwarded` (or `X-Forwarded-For`) values are set by trusted reverse proxies while the values to the left of that come from the client and intermediate proxies. That means that any values not set by trusted proxies are totally untrustworthy.

Your parsing code (which is the best I've seen, btw) throws an error if any part of the header is bad. But that means an attacker if an attacker violates the syntax with a spoofed header, the entire header is unusable -- even the parts added by trusted proxies.

I think that this should be a commented caveat, at least. Like, "the first trusted reverse proxy must drop any existing `Forwarded` header value before adding a new one". Or maybe require that reverse proxies validate the existing `Forwarded` syntax before adding a new value (but that might be too fanciful)

It would be even better if the header were salvageable. But if the header has a value [like](https://forum.nginx.org/read.php?29,275880) `for=injected;by=", for=real` ... what then? 

Some not-good ideas off the top of my head:
* Violate the RFC by disallowing comma in quoted-strings. Then separate on them and treat each part individually.
* Parse starting from the right. When a syntax error is hit, stop and return any good values found already.

**Comment by lpinca** [comment]
>  Like, "the first trusted reverse proxy must drop any existing Forwarded header value before adding a new one". Or maybe require that reverse proxies validate the existing Forwarded syntax before adding a new value (but that might be too fanciful)

Yes, I think that following the suggestion in point 3 of the [forum post](https://forum.nginx.org/read.php?29,275880,275880#msg-275880) makes sense.

From a parsing point of view, I think there is not much to do as the issue could happen at any point, even in the part added by the latest proxy.

**Comment by adam-p** [comment]
I ended up writing a blog post about this: https://adam-p.ca/blog/2022/03/forwarded-header-sabotage/ Probably nothing that you don't already know.

I don't really like solutions that depend on specific reverse proxy behaviour, since not all reverse proxies can be configured like that, and the default probably won't be that behaviour, so lots of people will still get burned.

But you're not wrong.

Anyway, thanks for the library and the response. I'll close this issue.
